/* AUTO-GENERATED by sync-engine-v2 next. Do not edit. */
import {
  defineGeneratedNextSyncConfig,
} from "@mintcd/sync-engine-v2/next";
import type {
  InferDatabase,
} from "@mintcd/sync-engine-v2/schema";

export const finalConfig = defineGeneratedNextSyncConfig({
  "formatVersion": 1,
  "databaseName": "sync-engine-v2-manual-row-sync",
  "endpoints": {
    "pull": "/api/sync/pull",
    "push": "/api/sync/push"
  },
  "serviceWorker": {
    "url": "/sync-engine-v2.sw.js",
    "syncTag": "manual-row-sync"
  },
  "schema": {
    "formatVersion": 1,
    "tables": {
      "notes": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "title": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          }
        }
      }
    },
    "schemaHash": "sha256:a8b150bd2591bffcf7cb9d3d566ce66d8353031ce32cbe4c6b3d6857914a8bb0"
  }
} as const);

export const replicaSchema = finalConfig.schema;
export type Database = InferDatabase<typeof replicaSchema>;
export type TableName = keyof Database;
export type Row<Table extends TableName> = Database[Table];
