/* AUTO-GENERATED by sync-engine-v2 next. Do not edit. */
import { syncServer } from "../../../sync/server";

export const runtime = "nodejs";

export async function POST(request: Request): Promise<Response> {
  return syncServer.pull(request);
}
