import { existsSync, readFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { transformSync } from "esbuild";

import {
  SYNC_CLIENT_CONFIG_FORMAT_VERSION,
} from "../../client";
import type { ReplicaSchemaContract } from "../../schema";
import type { NormalizedNextSyncConfig } from "./config";

export const GENERATED_FILE_BANNER =
  "/* AUTO-GENERATED by sync-engine-v2 next. Do not edit. */";

export interface GeneratedNextFiles {
  readonly config: {
    readonly path: string;
    readonly source: string;
  };
  readonly pullRoute: {
    readonly path: string;
    readonly source: string;
  };
  readonly pushRoute: {
    readonly path: string;
    readonly source: string;
  };
  readonly serviceWorker?: {
    readonly path: string;
    readonly source: string;
  };
}

export function generateNextFiles(
  config: NormalizedNextSyncConfig,
  schema: ReplicaSchemaContract,
): GeneratedNextFiles {
  const pullPath = path.join(config.routes.pullDirectory, "route.ts");
  const pushPath = path.join(config.routes.pushDirectory, "route.ts");
  return {
    config: {
      path: config.output.config,
      source: generateClientConfigSource(config, schema),
    },
    pullRoute: {
      path: pullPath,
      source: generateRouteSource(config, pullPath, "pull"),
    },
    pushRoute: {
      path: pushPath,
      source: generateRouteSource(config, pushPath, "push"),
    },
    ...(config.output.serviceWorker === undefined
      ? {}
      : {
        serviceWorker: {
          path: config.output.serviceWorker,
          source: generateServiceWorkerSource(config),
        },
      }),
  };
}

export function generateClientConfigSource(
  config: NormalizedNextSyncConfig,
  schema: ReplicaSchemaContract,
): string {
  const payload = {
    formatVersion: SYNC_CLIENT_CONFIG_FORMAT_VERSION,
    databaseName: config.client.databaseName,
    endpoints: {
      pull: config.routes.pullUrl,
      push: config.routes.pushUrl,
    },
    ...(config.serviceWorker.url === undefined
      ? {}
      : {
        serviceWorker: {
          url: config.serviceWorker.url,
          ...(config.serviceWorker.scope === undefined
            ? {}
            : { scope: config.serviceWorker.scope }),
          syncTag: config.serviceWorker.syncTag,
        },
      }),
    schema,
  } as const;
  const literal = JSON.stringify(payload, null, 2);

  return renderTemplateFile("client-config.template.ts", {
    __SYNC_ENGINE_V2_NEXT_CONFIG__: `${literal} as const`,
  });
}

export function generateRouteSource(
  config: NormalizedNextSyncConfig,
  routePath: string,
  method: "pull" | "push",
): string {
  const moduleSpecifier = serverModuleSpecifier(config, routePath);
  const importStatement =
    config.server.exportName === "default"
      ? `import syncServer from ${JSON.stringify(moduleSpecifier)};`
      : config.server.exportName === "syncServer"
        ? `import { syncServer } from ${JSON.stringify(moduleSpecifier)};`
        : `import { ${config.server.exportName} as syncServer } from ${JSON.stringify(moduleSpecifier)};`;

  return `${GENERATED_FILE_BANNER}
${importStatement}

export const runtime = "nodejs";

export async function POST(request: Request): Promise<Response> {
  return syncServer.${method}(request);
}
`;
}

export function generateServiceWorkerSource(
  config: NormalizedNextSyncConfig,
): string {
  const payload = {
    endpoints: {
      pull: config.routes.pullUrl,
      push: config.routes.pushUrl,
    },
    syncTag: config.serviceWorker.syncTag,
  } as const;

  return transpileServiceWorkerTemplate(
    renderTemplateFile("service-worker.template.ts", {
      __SYNC_ENGINE_V2_SERVICE_WORKER_CONFIG__: JSON.stringify(payload, null, 2),
    }),
  );
}

function transpileServiceWorkerTemplate(source: string): string {
  const body = source.startsWith(`${GENERATED_FILE_BANNER}\n`)
    ? source.slice(GENERATED_FILE_BANNER.length + 1)
    : source;
  const transformed = transformSync(body, {
    loader: "ts",
    target: "es2022",
    format: "esm",
    legalComments: "none",
  });
  return `${GENERATED_FILE_BANNER}\n${transformed.code}`;
}

function renderTemplateFile(
  name: string,
  replacements: Readonly<Record<string, string>>,
): string {
  return stripTemplateOnlySource(readTemplateFile(name)).replace(
    /\b__SYNC_ENGINE_V2_[A-Z_]+__\b/g,
    (placeholder) => {
      const replacement = replacements[placeholder];
      if (replacement === undefined) {
        throw new Error(`missing generated template value ${placeholder}`);
      }
      return replacement;
    },
  );
}

function readTemplateFile(name: string): string {
  const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.join(currentDirectory, "templates", name),
    path.join(currentDirectory, "next", "templates", name),
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return readFileSync(candidate, "utf8");
    }
  }

  throw new Error(
    `sync-engine-v2 next template ${JSON.stringify(name)} was not found`,
  );
}

function stripTemplateOnlySource(source: string): string {
  return source.replace(
    /^\/\/ sync-engine-v2-template-only-start\r?\n[\s\S]*?^\/\/ sync-engine-v2-template-only-end\r?\n?/gm,
    "",
  );
}

function serverModuleSpecifier(
  config: NormalizedNextSyncConfig,
  routePath: string,
): string {
  const configured = config.server.module;
  if (!configured.startsWith(".") && !path.isAbsolute(configured)) {
    return configured;
  }

  const absolute = resolveProjectModule(config.projectRoot, configured);
  const withoutExtension = absolute.replace(/\.(?:[cm]?[jt]sx?)$/i, "");
  let relative = path.relative(path.dirname(routePath), withoutExtension);
  relative = relative.split(path.sep).join("/");
  if (!relative.startsWith(".")) {
    relative = `./${relative}`;
  }
  return relative;
}

function resolveProjectModule(projectRoot: string, value: string): string {
  if (!path.isAbsolute(value)) {
    return path.resolve(projectRoot, value);
  }
  const parsed = path.parse(value);
  const hasExplicitVolume = parsed.root !== path.sep && parsed.root !== "/";
  return hasExplicitVolume
    ? value
    : path.join(projectRoot, value.replace(/^[/\\]+/, ""));
}
