/* AUTO-GENERATED by sync-engine-v2 next. Do not edit. */
import {
  defineGeneratedNextSyncConfig,
} from "@mintcd/sync-engine-v2/next";
import type {
  InferDatabase,
} from "@mintcd/sync-engine-v2/schema";

// sync-engine-v2-template-only-start
import type {
  GeneratedNextSyncConfig,
} from "@mintcd/sync-engine-v2/next";

declare const __SYNC_ENGINE_V2_NEXT_CONFIG__: GeneratedNextSyncConfig;
// sync-engine-v2-template-only-end
export const finalConfig = defineGeneratedNextSyncConfig(__SYNC_ENGINE_V2_NEXT_CONFIG__);

export const replicaSchema = finalConfig.schema;
export type Database = InferDatabase<typeof replicaSchema>;
export type TableName = keyof Database;
export type Row<Table extends TableName> = Database[Table];
