/* AUTO-GENERATED by sync-engine next. Do not edit. */
/* eslint-disable no-restricted-globals */

// sync-engine-template-only-start
export { };

interface SyncEngineServiceWorkerConfig {
  readonly endpoints: {
    readonly pull: string;
    readonly push: string;
  };
  readonly syncTag: string;
}

interface SyncEngineServiceWorkerMessageEvent {
  readonly data: unknown;
  readonly ports?: ReadonlyArray<{
    readonly postMessage: (message: unknown) => void;
  }>;
  readonly source?: {
    readonly postMessage?: (message: unknown) => void;
  } | null;
  readonly waitUntil: (promise: Promise<unknown>) => void;
}

interface SyncEngineServiceWorkerSyncEvent {
  readonly tag: string;
  readonly waitUntil: (promise: Promise<unknown>) => void;
}

interface SyncEngineServiceWorkerGlobalScope {
  readonly registration?: {
    readonly sync?: {
      readonly register?: (tag: string) => Promise<void>;
    };
  };
  readonly clients: {
    readonly claim: () => Promise<void>;
    readonly matchAll: (options: {
      readonly includeUncontrolled: boolean;
    }) => Promise<ReadonlyArray<{
      readonly postMessage: (message: unknown) => void;
    }>>;
  };
  readonly skipWaiting: () => void;
  readonly addEventListener: {
    (type: "install", listener: () => void): void;
    (
      type: "activate",
      listener: (event: { readonly waitUntil: (promise: Promise<unknown>) => void }) => void,
    ): void;
    (
      type: "message",
      listener: (event: SyncEngineServiceWorkerMessageEvent) => void,
    ): void;
    (
      type: "sync",
      listener: (event: SyncEngineServiceWorkerSyncEvent) => void,
    ): void;
  };
}

interface SyncEngineServiceWorkerRequestMessage {
  readonly requestId?: unknown;
  readonly endpoint?: unknown;
  readonly envelope?: unknown;
  readonly streamId?: unknown;
}

interface SyncEngineServiceWorkerReplyMessage {
  readonly type: string;
  readonly requestId?: string;
  readonly endpoint?: string;
  readonly envelope?: unknown;
  readonly error?: string;
  readonly syncTag?: string;
  readonly streamId?: string;
}

declare const self: SyncEngineServiceWorkerGlobalScope;
declare const __SYNC_ENGINE_V2_SERVICE_WORKER_CONFIG__: SyncEngineServiceWorkerConfig;
// sync-engine-template-only-end
const CONFIG: SyncEngineServiceWorkerConfig =
  __SYNC_ENGINE_V2_SERVICE_WORKER_CONFIG__;

self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener("message", (event) => {
  const data = event.data;
  if (data === null || typeof data !== "object") {
    return;
  }

  const type = Reflect.get(data, "type");
  if (type === "sync-engine:register-sync") {
    event.waitUntil(registerBackgroundSync());
    return;
  }

  if (type === "sync-engine:mutation") {
    event.waitUntil(
      requestMutationSync(readOptionalString(Reflect.get(data, "streamId"))),
    );
    return;
  }

  if (type !== "sync-engine:request") {
    return;
  }

  event.waitUntil(proxySyncRequest(data, event));
});

self.addEventListener("sync", (event) => {
  if (event.tag !== CONFIG.syncTag) {
    return;
  }
  event.waitUntil(notifyClients({
    type: "sync-engine:background-sync",
    syncTag: CONFIG.syncTag,
  }));
});

async function requestMutationSync(streamId: string | undefined): Promise<void> {
  try {
    await registerBackgroundSync();
  } catch {
    // Foreground clients can still push immediately when registration fails.
  }

  await notifyClients({
    type: "sync-engine:background-sync",
    syncTag: CONFIG.syncTag,
    ...(streamId === undefined ? {} : { streamId }),
  });
}

async function proxySyncRequest(
  data: SyncEngineServiceWorkerRequestMessage,
  event: SyncEngineServiceWorkerMessageEvent,
): Promise<void> {
  const requestId = typeof data.requestId === "string" ? data.requestId : "";
  const endpointName = data.endpoint === "push" ? "push" : "pull";
  const endpoint = CONFIG.endpoints[endpointName];

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify(data.envelope),
    });
    const text = await response.text();
    const body = text === "" ? null : JSON.parse(text);
    if (!response.ok) {
      throw new Error(
        body && typeof body.message === "string"
          ? body.message
          : `sync endpoint returned HTTP ${response.status}`,
      );
    }
    await reply(event, {
      type: "sync-engine:response",
      requestId,
      endpoint: endpointName,
      envelope: body,
    });
  } catch (error) {
    await reply(event, {
      type: "sync-engine:error",
      requestId,
      endpoint: endpointName,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

async function registerBackgroundSync() {
  const registration = self.registration;
  if (registration && registration.sync && registration.sync.register) {
    await registration.sync.register(CONFIG.syncTag);
  }
}

async function reply(
  event: SyncEngineServiceWorkerMessageEvent,
  message: SyncEngineServiceWorkerReplyMessage,
): Promise<void> {
  if (event.ports && event.ports[0]) {
    event.ports[0].postMessage(message);
    return;
  }
  if (event.source && event.source.postMessage) {
    event.source.postMessage(message);
    return;
  }
  await notifyClients(message);
}

async function notifyClients(
  message: SyncEngineServiceWorkerReplyMessage,
): Promise<void> {
  const clients = await self.clients.matchAll({ includeUncontrolled: true });
  for (const client of clients) {
    client.postMessage(message);
  }
}

function readOptionalString(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}
