import { SchemaGenerationError } from "./errors";
import type { ReplicaSchemaContract } from "./types";

export interface GenerateReplicaSchemaModuleOptions {
  readonly exportName?: string;
  readonly moduleSpecifier?: string;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const RESERVED_IDENTIFIERS = new Set([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);

export function generateReplicaSchemaModule(
  schema: ReplicaSchemaContract,
  options: GenerateReplicaSchemaModuleOptions = {},
): string {
  const exportName = options.exportName ?? "replicaSchema";
  if (!IDENTIFIER.test(exportName) || RESERVED_IDENTIFIERS.has(exportName)) {
    throw new SchemaGenerationError(
      `${JSON.stringify(exportName)} is not a valid generated export name`,
    );
  }

  const moduleSpecifier =
    options.moduleSpecifier ?? "@mintcd/sync-engine/schema";
  if (moduleSpecifier.trim() === "") {
    throw new SchemaGenerationError("moduleSpecifier must not be empty");
  }

  const serializedSchema = JSON.stringify(schema, null, 2);
  return [
    "/* AUTO-GENERATED by sync-engine. Do not edit. */",
    `import { defineReplicaSchema } from ${JSON.stringify(moduleSpecifier)};`,
    `import type { InferDatabase } from ${JSON.stringify(moduleSpecifier)};`,
    "",
    `export const ${exportName} = defineReplicaSchema(${serializedSchema} as const);`,
    "",
    `export type Database = InferDatabase<typeof ${exportName}>;`,
    "export type TableName = keyof Database;",
    "export type Row<Table extends TableName> = Database[Table];",
    "",
  ].join("\n");
}
